export const facilityMap = [
    {
        id: 1,
        name: "OCEAN SUITE",
        area: "85.8 m2",
        price: "1000",
        maxPersons: "10",
        rentalType: "Ngày",
    },
    {
        id: 2,
        name: "OCEAN SUITE",
        area: "85.8 m2",
        price: "1000",
        maxPersons: "10",
        rentalType: "Ngày",
    },
    {
        id: 3,
        name: "OCEAN SUITE",
        area: "85.8 m2",
        price: "1000",
        maxPersons: "10",
        rentalType: "Ngày",
    },
    {
        id: 4,
        name: "OCEAN SUITE",
        area: "85.8 m2",
        price: "1000",
        maxPersons: "10",
        rentalType: "Ngày",
    },
    {
        id: 5,
        name: "OCEAN SUITE",
        area: "85.8 m2",
        price: "1000",
        maxPersons: "10",
        rentalType: "Ngày",
    },
    {
        id: 5,
        name: "OCEAN SUITE",
        area: "85.8 m2",
        price: "1000",
        maxPersons: "10",
        rentalType: "Ngày",
    },
    {
        id: 7,
        name: "OCEAN SUITE",
        area: "85.8 m2",
        price: "1000",
        maxPersons: "10",
        rentalType: "Tháng",
    },
]

